Check for open external ports before starting net
This is acheived by starting a local TCP server and a local UDP server
on the ports required to be external and sending a single request-reply
round-trip. If this fails for either the TCP and UDP ports (the external
port and the discovery port), then we print a "nice" error message. This
can false-positive, but only for users who really know what they're
doing with their firewalls or port-forwarding so there is a way to
opt-out with another flag. This is documented in the error message.

Tested only on a network where I can't open ports. Will test more
thoroughly on a better network later.

Example error message:

```
Failed to verify that your ports were open. If your ports aren't accessible externally, you could be banned from the Coda network without realizing it!

This could be a false positive. If you know what you are doing, please add `-no-check-open-ports` and we will skip this check.

More details:

Error: could not access ports externally
External port check failed: IO error: (monitor.ml.Error
 ("connection attempt timeout" 67.160.217.218:8302 src/tcp.ml:120:11)
 ("Raised at file \"src/error.ml\" (inlined), line 9, characters 14-30"
  "Called from file \"src/error.ml\" (inlined), line 5, characters 2-50"
  "Called from file \"src/tcp.ml\", line 120, characters 11-76"
  "Called from file \"src/job_queue.ml\" (inlined), line 131, characters 2-5"
  "Called from file \"src/job_queue.ml\", line 170, characters 6-47"
  "Caught by monitor try_with_or_error"))
Discover port check failed: Could not reach the server (timed out)

To resolve:

Are your ports open?
Find your local ip address with `ifconfig`.
Get miniupnpc (you can download via your favorite package manager).

Then run:
$ upnpc -a <your local ip> 8302 8302 tcp
$ upnpc -a <your local ip> 8303 8303 udp

If this doesn't work, check out portforwarding.com for more tips or go to Coda discord chat for help.
```