Avoid relative urls in the .gitmodules file (#2174)
This change makes it easier for new contributors to contribute to coda.

After I forked coda and did git submodule init && git submodule update --recursive, I had a failure:

```
ERROR: Repository not found.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:rahulmutt/async_kernel'  ...
```

It turns out that the submodule urls are defined relatively so I had to fork all the submodules in order to make it work.

This PR updates .gitmodules to use absolute instead of relative urls so that contributors don't have to fork unnecessarily.